if(CONFIG_USERSPACE)

  zephyr_linker_section(NAME kobject_data GROUP ${K_OBJECTS_GROUP} NOINPUT)
  
  zephyr_linker_section_configure(
    SECTION kobject_data
    SYMBOLS z_kobject_data_begin
    )
  
  if(CONFIG_DYNAMIC_OBJECTS)
    #generated by gperf, this avoids errors for the first build.
    #Also, we dont have KOBJECT_DATA_SZ for the first build
    zephyr_linker_section_configure(
      SECTION kobject_data
      SYMBOLS _thread_idx_map
      MIN_SIZE ${CONFIG_MAX_THREAD_BYTES}
      PASS NOT LINKER_ZEPHYR_PREBUILT
      PASS NOT LINKER_ZEPHYR_FINAL
      )
    zephyr_linker_section_configure(
      SECTION kobject_data
      #OFFSET ${CONFIG_MAX_THREAD_BYTES}
      SYMBOLS _kobject_data_area_start _kobject_data_area_end
      PASS NOT LINKER_ZEPHYR_PREBUILT
      PASS NOT LINKER_ZEPHYR_FINAL
      )
  endif()

  #/* During LINKER_KOBJECT_PREBUILT and LINKER_ZEPHYR_PREBUILT,
	# * space needs to be reserved for the rodata that will be
	# * produced by gperf during the final stages of linking.
	# * The alignment and size are produced by
	# * scripts/build/gen_kobject_placeholders.py. These are here
	# * so the addresses to kobjects would remain the same
	# * during the final stages of linking (LINKER_ZEPHYR_FINAL).
	# */

  set(KOBJECT_DATA_ALIGN 4)
  set(KOBJECT_DATA_SZ    0x398)


  if(CONFIG_DYNAMIC_OBJECTS)
    zephyr_linker_section_configure(
      SECTION kobject_data
      SYMBOLS _thread_idx_map
      PASS LINKER_ZEPHYR_PREBUILT # no size ? This is what kobject-data.ld does.
      )
  endif()
    
  zephyr_linker_section_configure(
    SECTION kobject_data
    INPUT
    ".kobject_data.data*"
    ".kobject_data.sdata*"
    PASS LINKER_ZEPHYR_FINAL
    PASS LINKER_ZEPHYR_PREBUILT
    ALIGN KOBJECT_DATA_ALIGN
    MIN_SIZE KOBJECT_DATA_SZ
    MAX_SIZE KOBJECT_DATA_SZ
    SYMBOLS _kobject_data_area_start _kobject_data_area_end
    )

    #This seems to be used only for a size-check, which is already don in MAX_SIZE.
  #zephyr_linker_symbol(
  #  SYMBOL
  #  _kobject_data_area_used
  #  EXPR
  #  "(@_kobject_data_area_end@ - @_kobject_data_area_start@)"
  #  )
endif()
